In [36]:
import pandas as pd

joinData1 = pd.read_csv("../dataProblem/joindata1.csv", encoding="utf-8")

joinData2 = pd.read_csv("../dataProblem/joindata2.csv", encoding="cp949")

joindata = pd.merge(left = joinData1, 
                    right = joinData2,  
                    how = 'inner', 
                    on = 'suta_tin' )

joindata['new_sutatin'] = joinData1.mata_tin

joinData1['new_sutatin'] = joindata.new_sutatin

resultData = joinData1

In [44]:
resultData

,mata_tin,mata_txpr_sex_cd,mate_mdf_yn,mate_srcs_cntn,mem_rit_cd,rit_end_dt,rit_strt_dt,suta_tin,suta_txpr_sex_cd,new_sutatin
0,153601000000,3,Y,대법원가족관계,2,99991231,20190107,153403000000,2,1.536010e+11
1,154102000000,3,Y,대법원가족관계,1,99991231,20190107,153460000000,1,1.541020e+11
2,153500000000,3,Y,대법원가족관계,2,99991231,20190107,154202000000,2,NaN
3,155000000000,3,Y,대법원가족관계,2,99991231,20190107,154302000000,2,NaN
4,153500000000,3,Y,대법원가족관계,2,99991231,20190107,153603000000,2,NaN
5,100026000000,3,Y,대법원가족관계,1,99991231,20190107,153103000000,1,NaN
6,153500000000,3,Y,대법원가족관계,2,99991231,20190107,154302000000,2,NaN
7,153500000000,3,Y,대법원가족관계,2,99991231,20190107,153202000000,2,NaN
8,153500000000,3,Y,대법원가족관계,2,99991231,20190107,153302000000,2,NaN
9,153500000000,3,Y,대법원가족관계,2,99991231,20190107,154802000000,2,NaN